### ISSUE TITLE
R / Line Plot - strange looking plot

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/scripting-templates#9]
Though the data looks rather clean and the configuration of the plot is very simple (x and y values, default for the rest), the result plot looks very strange.
Example workflow in the issue folder under
/Volumes/tds/software+tools/Knime/Issues/Templates/
![screen shot 2015-11-13 at 09 46 22](https://cloud.githubusercontent.com/assets/740926/11142190/d07888f4-89eb-11e5-99c1-459a6704aec5.png)

**Comment by stoeter** [comment]
The problem is that the x axis in not properly scaled and by default starts at 0

The temp solution is to enter an additional line into the template/R code to scale the x axis (e.g.):
xAxisMin <- 9700
xAxisMax <- 9800
p <- p + scale_x_continuous(limits = c(xAxisMin,xAxisMax), name = yAxisLabel) #use e.g. limits = c(0,100)

The following things need to be changed:
- extend the GUI to let the user enter limits for the x-axis
- check user-defined values and/or set default axis limits to min to mas of that parameter
- find solution for the fact that the template in general allows string columns as x-axis (ok, if x is actually a categorial variable, and the plot should not per se be only an xy-scatter plot), but then the min/max value default will make errors

I will take care of this when I am back...

**Comment by niederle** [comment]
The scaling should be automatically defined by ggplot.
I see the problem in these two lines of code:

`p <- p + scale_x_discrete(name = xFactorCol)`
`p <- p + scale_y_continuous(limits = yAxisScale, name = yAxisLabel)`

In this case they only serve to set the axis title. Commenting out these lines results in a nice looking plot. The labels should instead be set with labs(x = ..., y = ...)

**Comment by stoeter** [comment]
fixed issue as suggested by using labs()
scaling of x axis is complicated for now, because in most cases a x will be string anyway...
